### ISSUE TITLE
Communication with prom-aggregation-gateway

### ISSUE THREAD

**Issue by benbenedek** [weaveworks/promjs#20]
Hi,
Thanks for creating and open-sourcing this awesome lib. 

I was wondering if you have a recommended way (or an interface to impl) for communication with prom-aggregation-gateway. I think this could be useful for this project.

Thanks again.

**Comment by mrzacarias** [comment]
Hi there @benbenedek, joining you on the group of people thankfully for this great lib being open-sourced :)

About the communication with the prom agg gateway, I'm having no trouble with using a very simple post request using the `registry.metrics()` output as the payload:
```
  var xhr = new XMLHttpRequest()
  let metricsEndpoint = promGatewayURL + `/api/ui/metrics`;
  xhr.open('POST', metricsEndpoint, true)
  xhr.setRequestHeader("Content-Type", "text/plain;charset=UTF-8");
  xhr.addEventListener('load', () => {
    console.log(metricsEndpoint, "prometheus-gateway response", xhr.status, xhr.responseText);
  });
  xhr.send(promRegistry.metrics());
```

**Comment by ngrkishore** [comment]
@mrzacarias , @benbenedek ,

What's promGatewayURL in the above code. Can you clarify if PromGateway should be running on server to make it work? I am using promjs library in Angular application. Not sure how to export these metrics so that they are available in "/metrics" endpoint. Please let me know how to do it.

**Comment by jpellizzari** [comment]
@ngrkishore Yes the gateway needs to be running on the server. Prometheus does a request as an HTTP client, so it will not be able to scrape metrics in a browser.

Please see my response here: https://github.com/weaveworks/promjs/issues/24

Closing this issue.
