### ISSUE TITLE
Note non-standard path

### ISSUE THREAD

**Issue by bboreham** [weaveworks/promjs#22]
As noted at https://github.com/weaveworks/prom-aggregation-gateway/pull/31, the path `/api/ui/metrics` is something Weaveworks picked, and does not match `/metrics/` which someone using the Prometheus push gateway would expect.

So we should at least note the mismatch and perhaps make it configurable.

**Comment by bboreham** [comment]
This isn't necessary now #31 is merged.

**Comment by jpellizzari** [comment]
This package does not do any network stuff (or at least it isn't supposed to). I think that URL is being defined in Weave Cloud.
