### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by ngrkishore** [weaveworks/promjs#24]
I am using this library in Angular application. I can see the metrics in the browser by logging in each component.
I am not sure how/what to implement in Angular so that Prometheus can pick these metrics by "/metrics" url end point.
Any ideas. Please share me some sample code if anyone has done it already.

**Comment by jpellizzari** [comment]
Hello @ngrkishore, 

Prometheus will not be able to scrape metrics from a browser. You will need to push metrics from the browser up to a push gateway. Here are some links to push gateway implementations:

https://github.com/weaveworks/prom-aggregation-gateway

https://github.com/prometheus/pushgateway

Let me know if that answers your question. Closing for mow.
