### ISSUE TITLE
lodash usage contributes to ~71kb (minified) when targetting Cloudflare Workers runtime

### ISSUE THREAD

**Issue by vlovich** [weaveworks/promjs#51]
I'm using promjs with some code on Cloudflare workers and I noticed that lodash contributes ~71kb of bloat (promjs without lodash is otherwise 9kb). For example, I think `lodash.filter`/`lodash.each`/`lodash.reduce`/`lodash.find`/`lodash.map` are completely redundant since ES arrays offer those out of the box I think. `lodash.sum` can be expressed in terms of `reduce`. `lodash.isEqual` could be replacable with a custom version of since it's just being used to compare two arrays of strings I think (& even a nested one wouldn't be hard).

I'm sure other pieces might be difficult to tease out but it would be nice because of how heavy a dependency lodash is.

FWIW I'm using esbuild. I've tried https://www.npmjs.com/package/@optimize-lodash/esbuild-plugin and it makes no difference to the minified size.

**Comment by MailboxArsonist** [comment]
Hey @thibmeu Is there any update on this? I can see that there is a PR up for it. Thanks

**Comment by thibmeu** [comment]
@MailboxArsonist I don't have merge permission, and the PR has to be check by the maintainer @dholbach. In the meantime, I've put out a forked npm package [promjs-worker](https://www.npmjs.com/package/promjs-worker) if that's helpful.

**Comment by thibmeu** [comment]
@dholbach this should be good to close once there is a release which is cut. Is there a specific process for cutting the release apart from tagging and updating package.json? I don't know to what extent this is automated.

**Comment by dholbach** [comment]
I don't maintain `promjs`- I was merely trying to help out in a few instances.

 @jpellizzari might be able to help.

**Comment by jpellizzari** [comment]
> @jpellizzari any chance you might be able to help in getting a release for this? Thanks

Release published :+1:

**Comment by jpellizzari** [comment]
Closed by `v0.4.2`
